import { JBProject } from "./dataTypes";
import { v4 as uuidv4 } from "uuid";

export const Projects: JBProject[] = [
  {
    id: "1",
    title: "LinkedIn Clone",
    codeLink: "https://github.com/jablancTheDesigner/jpb-linkedin-clone",
    logo: null,
    thumbnail: null,
    gallery: [],
    tools: {
      react: true,
      sass: true,
      css: false,
      html: false,
      js: true,
      angular: false,
      photoshop: false,
      illustrator: false,
      firebase: true
    },
    url: "https://linkedin-clone-6fc78.firebaseapp.com/",
    featured: true,
    color: "#000000",
    type: ["development"],
  },
  {
    id: "2",
    title: 'E-Commerce App',
    codeLink: "https://github.com/jablancTheDesigner/puffessional",
    logo: null,
    thumbnail: null,
    gallery: [],
    tools: {
      react: true,
      sass: true,
      css: false,
      html: false,
      js: true,
      angular: false,
      photoshop: false,
      illustrator: false,
      firebase: true
    },
    url: "https://puffessional.netlify.app/",
    featured: true,
    color: "#000000",
    type: ["development"],
  },
  {
    id: "3",
    title: 'Blogging App',
    codeLink: "https://github.com/jablancTheDesigner/jpb-blog",
    logo: null,
    thumbnail: null,
    gallery: [],
    tools: {
      react: true,
      sass: true,
      css: false,
      html: false,
      js: true,
      angular: false,
      photoshop: false,
      illustrator: false,
      firebase: true
    },
    url: "https://jpb-blog.netlify.app/",
    featured: true,
    color: "#000000",
    type: ["development"],
  },
  {
    id: "4",
    title: "Slide Out Navigation",
    codeLink: "https://github.com/jablancTheDesigner/minimalist-nav",
    logo: null,
    thumbnail: null,
    gallery: [],
    tools: {
      react: false,
      sass: true,
      css: false,
      html: true,
      js: true,
      angular: false,
      photoshop: false,
      illustrator: false,
      firebase: false
    },
    url: "https://jablancthedesigner.github.io/minimalist-nav/",
    featured: true,
    color: "#000000",
    type: ["logo"],
  },
  {
    id: "5",
    title: "Jay Photography",
    client: "Jay",
    codeLink: null,
    logo: null,
    thumbnail: null,
    gallery: [],
    tools: {
      react: false,
      sass: false,
      css: false,
      html: false,
      js: false,
      angular: false,
      photoshop: false,
      illustrator: true,
      firebase: false
    },
    url: null,
    featured: true,
    color: "#000000",
    type: ["logo"],
  },
  {
    id: "6",
    title: "Kloud 9 Kicks",
    client: "Gabe B.",
    codeLink: null,
    logo: null,
    thumbnail: null,
    gallery: [],
    tools: {
      react: false,
      sass: false,
      css: false,
      html: false,
      js: false,
      angular: false,
      photoshop: false,
      illustrator: true,
      firebase: false
    },
    url: null,
    featured: true,
    color: "#000000",
    type: ["logo"],
  },
];
